// frontend-nextjs/components/TodoList.tsx
import { Database } from '@/lib/schema'
import { Session, SupabaseClient } from '@supabase/supabase-js'
import { useEffect, useState } from 'react'

type Todos = Database['public']['Tables']['todos']['Row']

export default function TodoList({
  session,
  supabase,
}: {
  session: Session
  supabase: SupabaseClient<any>
}) {
  const [todos, setTodos] = useState<Todos[]>([])
  const [newTaskText, setNewTaskText] = useState('')
  const [errorText, setErrorText] = useState('')

  const user = session.user

  useEffect(() => {
    const fetchTodos = async () => {
      const { data: todos, error } = await supabase
        .from('todos')
        .select('*')
        .order('id', { ascending: true })

      if (error) console.log('error', error)
      else setTodos(todos)
    }

    fetchTodos()
  }, [supabase])

  const addTodo = async (taskText: string) => {
    let task = taskText.trim()
    if (task.length) {
      const { data: todo, error } = await supabase
        .from('todos')
        .insert({ task, user_id: user.id })
        .select()
        .single()

      if (error) {
        setErrorText(error.message)
      } else {
        setTodos([...todos, todo])
        setNewTaskText('')
      }
    }
  }

  const deleteTodo = async (id: number) => {
    try {
      await supabase.from('todos').delete().eq('id', id).throwOnError()
      setTodos(todos.filter((x) => x.id != id))
    } catch (error) {
      console.log('error', error)
    }
  }

  return (
    <div className="w-full">
      <h1 className="mb-12">Todo List.</h1>
      <form
        onSubmit={(e) => {
          e.preventDefault()
          addTodo(newTaskText)
        }}
        className="flex gap-2 my-2"
      >
        <input
          className="rounded w-full p-2"
          type="text"
          placeholder="make coffee"
          value={newTaskText}
          onChange={(e) => {
            setErrorText('')
            setNewTaskText(e.target.value)
          }}
        />
        <button className="btn-black" type="submit">
          Add
        </button>
      </form>
      {!!errorText && <Alert text={errorText} />}
      <div className="bg-white shadow overflow-hidden rounded-md">
        <ul>
          {todos.map((todo) => (
            <Todo key={todo.id} todo={todo} onDelete={() => deleteTodo(todo.id)} supabase={supabase} />
          ))}
        </ul>
      </div>
    </div>
  )
}

const Todo = ({
  todo,
  onDelete,
  supabase,
}: {
  todo: Todos
  onDelete: () => void
  supabase: SupabaseClient<any>
}) => {
  const [isCompleted, setIsCompleted] = useState(todo.is_complete)

  const toggle = async () => {
    try {
      const { data } = await supabase
        .from('todos')
        .update({ is_complete: !isCompleted })
        .eq('id', todo.id)
        .throwOnError()
        .select()
        .single()

      if (data) setIsCompleted(data.is_complete)
    } catch (error) {
      console.log('error', error)
    }
  }

  return (
    <li className="w-full block cursor-pointer hover:bg-200 focus:outline-none focus:bg-200 transition duration-150 ease-in-out">
      <div className="flex items-center px-4 py-4 sm:px-6">
        <div className="min-w-0 flex-1 flex items-center">
          <div className="text-sm leading-5 font-medium truncate">{todo.task}</div>
        </div>
        <div>
          <input
            className="cursor-pointer"
            onChange={(e) => toggle()}
            type="checkbox"
            checked={isCompleted ? true : false}
          />
        </div>
        <button
          onClick={(e) => {
            e.preventDefault()
            e.stopPropagation()
            onDelete()
          }}
          className="w-4 h-4 ml-2 border-2 hover:border-black rounded"
        >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="gray">
            <path
              fillRule="evenodd"
              d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
              clipRule="evenodd"
            />
          </svg>
        </button>
      </div>
    </li>
  )
}

const Alert = ({ text }: { text: string }) => (
  <div className="rounded-md bg-red-100 p-4 my-3">
    <div className="text-sm leading-5 text-red-700">{text}</div>
  </div>
)

// frontend-vue/src/components/TodoList.vue
<script setup>
import { ref, onMounted } from 'vue'
import { supabase } from '../supabase'

const props = defineProps(['session'])

const todos = ref([])
const newTaskText = ref('')
const errorText = ref('')

const fetchTodos = async () => {
  const { data, error } = await supabase
    .from('todos')
    .select('*')
    .order('id', { ascending: true })

  if (error) console.log('error', error)
  else todos.value = data
}

onMounted(() => {
  fetchTodos()
})

const addTodo = async () => {
  const task = newTaskText.value.trim()
  if (task.length) {
    const { data, error } = await supabase
      .from('todos')
      .insert({ task, user_id: props.session.user.id })
      .select()
      .single()

    if (error) {
      errorText.value = error.message
    } else {
      todos.value.push(data)
      newTaskText.value = ''
    }
  }
}

const deleteTodo = async (id) => {
  try {
    await supabase.from('todos').delete().eq('id', id).throwOnError()
    todos.value = todos.value.filter((x) => x.id != id)
  } catch (error) {
    console.log('error', error)
  }
}

const toggleDone = async (todo) => {
  try {
    const { data, error } = await supabase
      .from('todos')
      .update({ is_complete: !todo.is_complete })
      .eq('id', todo.id)
      .select()
      .single()
      
    if (error) throw error
    
    todo.is_complete = data.is_complete
  } catch (error) {
    console.log('error', error)
  }
}
</script>

<template>
  <div class="todo-app">
    <h1>Todo List.</h1>
    
    <div class="input-group">
      <input 
        v-model="newTaskText" 
        @keyup.enter="addTodo" 
        placeholder="make coffee" 
      />
      <button @click="addTodo">Add</button>
    </div>

    <div v-if="errorText" class="error-alert">
      {{ errorText }}
    </div>

    <ul class="todo-list">
      <li v-for="todo in todos" :key="todo.id" :class="{ done: todo.is_complete }">
        <span @click="toggleDone(todo)">{{ todo.task }}</span>
        <button class="delete-btn" @click="deleteTodo(todo.id)">x</button>
      </li>
    </ul>
  </div>
</template>

<style scoped>
.todo-app {
  font-family: Arial, sans-serif;
  margin: 0 auto;
  text-align: left;
}

h1 {
  text-align: center;
  color: #42b883;
  margin-bottom: 2rem;
}

.input-group {
  display: flex;
  gap: 10px;
  margin-bottom: 20px;
}

input {
  flex: 1;
  padding: 8px;
  border: 1px solid #ccc;
  border-radius: 4px;
}

button {
  padding: 8px 16px;
  background-color: #42b883;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

button:hover {
  background-color: #33a06f;
}

.error-alert {
  color: #721c24;
  background-color: #f8d7da;
  border-color: #f5c6cb;
  padding: .75rem 1.25rem;
  margin-bottom: 1rem;
  border: 1px solid transparent;
  border-radius: .25rem;
}

.todo-list {
  list-style: none;
  padding: 0;
}

li {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px;
  background: #2f2f2f;
  margin-bottom: 5px;
  border-radius: 4px;
}

li span {
  cursor: pointer;
  flex: 1;
}

li.done span {
  text-decoration: line-through;
  color: #888;
}

.delete-btn {
  background-color: #ff4444;
  padding: 4px 8px;
  margin-left: 10px;
}

.delete-btn:hover {
  background-color: #cc0000;
}
</style>
